name = "cloud-mail-dev"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[dev]
ip = "0.0.0.0"

[[d1_databases]]
binding = "db"
database_name = "email_d1"
database_id = "9a259f51-b4a1-4401-ba1c-feda6992cdef"

[[kv_namespaces]]
binding = "kv"
id = "fe2b8a573a864313ae759c027dcefed6"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = "email"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true


[vars]
orm_log = false
domain = ["example.com", "example2.com", "example3.com", "example4.com"]
admin = "admin@example.com"
jwt_secret = "b7f29a1d-18e2-4d3b-941f-f6b2c97c02fd"
